#!/bin/sh
echo "ProxyChains-3.1 (http://proxychains.sf.net)"
if [ $# = 0 ] ; then
	echo "	usage:"
	echo "		proxychains <prog> [args]"
	exit
fi
export http_proxy=207.246.87.236:3128
export https_proxy=207.246.87.236:3128
exec "$@"
