#!/bin/sh
echo "ProxyChains-3.1 (http://proxychains.sf.net)"
if [ $# = 0 ] ; then
	echo "	usage:"
	echo "		proxychains <prog> [args]"
	exit
fi
export http_proxy=127.0.0.1:1083
export https_proxy=127.0.0.1:1083
exec "$@"
